config/routes.rb
Rails.application.routes.draw do
  root 'donations#index'
  resources :donors
  resources :organizations
  resources :donations

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  belongs_to :donor
  belongs_to :organization

  validates :amount, numericality: { greater_than: 0 }
  validates :date, presence: true

  default_scope -> { order('date DESC') }
end

app/models/donor.rb
class Donor < ActiveRecord::Base
  has_many :donations
  has_many :organizations, through: :donations

  validates :name, presence: true

  default_scope -> { order('name ASC') }

  def fuzzy_match(donor)
    search_array = []
    Donor.all.each do | donor |
      search_array << donor.name
    end
    FuzzyMatch.new(search_array).find("#{donor}")
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :donations
  has_many :donors, through: :donations

  default_scope -> { order('name ASC') }

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]
  before_action :set_donor, only: [:create, :edit]
  before_action :set_organization, only: [:create, :edit]

  def index
    @donations = Donation.take(10)
  end

  def new
    @donation = Donation.new
    @donors = Donor.all
    @organizations = Organization.all
  end

  def edit
    @donation = Donation.find(params[:id])
    @donors = Donor.all
    @organizations = Organization.all
  end

  def show
    @organization = @donation.donor
    @donor = @donation.donor
  end

  def create
    @donation = Donation.new(donation_params)
    @donors = Donor.all
    @organizations = Organization.all
    if @donation.save
      flash[:notice] = 'Donation added!'
      redirect_to @donation
    else
      flash[:notice] = "Donation could not be saved"
      render :new
    end
  end

  def update
    if @donation.update(donation_params)
      flash[:notice] = "Donation updated!"
      redirect_to @donation
    else
      flash[:notice] = "Donation could not be updated"
      render :edit
    end
  end

  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_path, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_organization
    @organization = Organization.find_by(params[:organization_id])
  end

  def set_donor
    @donor = Donor.find_by(params[:donor_id])
  end

  def set_donation
    @donation = Donation.find(params[:id])
  end

  def donation_params
    params.require(:donation).permit(:amount, :date, :organization_id, :donor_id)
  end
end

app/controllers/donors_controller.rb
class DonorsController < ApplicationController
  before_action :set_donor, only: [:show, :edit, :update, :destroy]

  def index
    @donors = Donor.paginate(page: params[:page], per_page: 20)
  end

  def show
  end

  def new
    @donor = Donor.new
  end

  def edit
  end

  def create
    @donor = Donor.new(donor_params)
    if @donor.save
      flash[:success] = 'Donor added!'
      # redirect_to @donor
    else
      flash[:notice] = "Donor could not be saved"
      render :new
    end
  end

  def update
    if @donor.update(donor_params)
      flash[:success] = "Donor updated!"
      # redirect_to @donor
    else
      flash[:notice] = "Donor could not be updated"
      render :edit
    end
  end

  def destroy
    @donor.destroy
    respond_to do |format|
      format.html { redirect_to donors_path, notice: 'Donor was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private

  def set_donor
    @donor = Donor.find(params[:id])
  end

  def donor_params
    params.require(:donor).permit(:name)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  def index
    @organizations = Organization.paginate(page: params[:page], per_page: 20)
  end

  def show
  end

  def new
    @organization = Organization.new
  end

  def edit
  end

  def create
    @organization = Organization.new(organization_params)
    if @organization.save
      flash[:success] = 'Organization added!'
      redirect_to @organization
    else
      flash[:notice] = "Organization could not be saved"
      render :new
    end
  end

  def update
    if @organization.update(organization_params)
      flash[:success] = "Organization updated!"
      redirect_to @organization
    else
      flash[:notice] = "Organization could not be updated"
      render :edit
    end
  end

  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_path, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_organization
    @organization = Organization.find(params[:id])
  end

  def organization_params
    params.require(:organization).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/donors_helper.rb
module DonorsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/donations/_form.html.erb
<%= form_for(@donation) do |f| %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% @donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :donor %><br>
    <%= f.select :donor_id, options_for_select(@donors.map{ |donor| [donor.name, donor.id]} ) %>
  </div>

  <div class="field">
    <%= f.label :organization %><br>
    <%= f.select :organization_id, options_for_select(@organizations.map{ |organization| [organization.name, organization.id]} ) %>
  </div>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_field :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h2>Edit A Donation</h2>

<p>You are editing information for a donation made by <%= @donation.donor.name %> to <%= @donation.organization.name %> in the amount of $<%= @donation.amount %> on <%= @donation.date.strftime("%m/%d/%Y") %>.<br></p>

<%= render 'form' %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<%= link_to 'New Donation', new_donation_path(@donation), class: "button", id: "new_donation_link", remote: true %>

<h2>Recent donations:</h2>

<% @donations.each do |donation| %>
  <ul class="money">
  <% unless donation.donor == nil || donation.organization == nil %>
    <li class="money"><%= link_to donation.donor.name, donor_path(donation.donor.id) %> to <%= link_to donation.organization.name, organization_path(donation.organization.id) %> in the amount of $<%= link_to donation.amount, donation_path(donation.id)%> on <%= donation.date.strftime("%m/%d/%Y") %>.</li>
  <% end %>
  </ul>
<% end %>

app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form' %>

<%= link_to 'Back', donations_path %>

app/views/donations/new.js.erb
$('#new_donation_link').hide().after('<%= j render("form") %>');

app/views/donations/show.html.erb
<%= link_to 'Edit Donation', edit_donation_path(@donation.id), class: "button tiny" %>
<%= link_to 'Destroy Donation', @donation, method: :delete, data: { confirm: 'Are you sure?' }, class: "button tiny" %>

<p>$<%= @donation.amount %>
made on <%= @donation.date.strftime("%m/%d/%Y") %>
from <%= link_to @donation.donor.name, donor_path(@donation.donor.id) %> to <%= link_to @donation.organization.name, organization_path(@donation.organization.id) %></p>

<%= link_to 'New Donation', new_donation_path(@donation), class: "button" %>
<%= link_to 'Back', donations_path, class: "button" %>

app/views/donors/_donor.html.erb
<li id="<%= dom_id donor %>">
    <%= link_to donor.name, donor %>
  | (<%= donor.organizations.count%>)
  | <%= link_to 'Edit', edit_donor_path(donor.id), id: 'donor_edit_id', remote: true %>
  | <%= link_to 'Destroy', donor, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
</li>

app/views/donors/_form.html.erb
<%= form_for(@donor, remote: true) do |f| %>
  <% if @donor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donor.errors.count, "error") %> prohibited this donor from being saved:</h2>

      <ul>
      <% @donor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donors/create.js.erb
$("#new_donor").remove();
$("#new_donor_link").show();
$("#donor_index ul").append("<%= j render(@donor) %>");

app/views/donors/destroy.js.erb
$("#<%= dom_id @donor %>").remove();

app/views/donors/edit.html.erb
<h1>Edit A Donor</h1>

<%= render 'form' %>

<%= link_to 'Show', @donor %> |
<%= link_to 'Back', donors_path %>

app/views/donors/edit.js.erb
$("#<%= dom_id @donor %>").html("<%= j render('form') %>")

app/views/donors/index.html.erb
<h1>Donors</h1>

<%= link_to 'New Donor', new_donor_path, class: "button", id: "new_donor_link", remote: true %>
<%= link_to 'Back', donations_path, class: "button" %>

<div id="donor_index">
<ul>
  <% @donors.each do |donor| %>
    <%= render donor %>
  <% end %>
</ul>
</div>

<%= will_paginate %>

app/views/donors/new.html.erb
<h1>New Donor</h1>

<%= render 'form' %>

<%= link_to 'Back', donors_path %>

app/views/donors/new.js.erb
$('#new_donor_link').hide().after('<%= j render("form") %>');

app/views/donors/show.html.erb
<h2 id="name_headline"><%= @donor.name %></h2>

<% if @donor.donations.count > 0 %>
  <% @donor.donations.each do |donation| %>
    <ul>
      <% unless donation.organization == nil %>
        <li>$<%= donation.amount %> on <%= donation.date.strftime("%m/%d/%Y") %> to <%= link_to donation.organization.name, organization_path(donation.organization.id) %> | <%= link_to 'Edit', edit_donation_path(donation.id) %> | <%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></li>
      <% end %>
    </ul>
  <% end %>
<% else %>
  <p>No donations to show.</p>
<% end %>

<%= link_to 'New Donation', new_donation_path(@donation), class: "button" %>

<%= link_to 'Back', donors_path, class: "button" %>

app/views/donors/update.js.erb
$("#<%= dom_id @donor %>").html("<%= j render(@donor) %>")

// replace old name with new name where-ever it appears
// $('h2#name_headline').replaceWith('<h2 id="name_headline"><%= @donor.name %></h2>');

app/views/layouts/_navbar.html.erb
<div class="row">
  <div class="large-12 columns">
    <div class="nav-bar right">
      <ul class="button-group">
        <li><a href="/" class="button">Home</a></li>
        <li><a href="/donors" class="button">Browse Donors</a></li>
        <li><a href="/organizations" class="button">Browse Organizations</a></li>
      </ul>
    </div>
    <h1 id="logo">Follow the Money</h1>
    <hr/>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href='https://fonts.googleapis.com/css?family=Calligraffitti' rel='stylesheet' type='text/css'>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Follow the Money" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
    <div class="row">
      <div class="large-12 columns">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application_backup.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FollowTheMoney</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/create.html.erb
<h1>Organizations#create</h1>
<p>Find me in app/views/organizations/create.html.erb</p>

app/views/organizations/edit.html.erb
<h1>Edit An Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<%= link_to 'New Organization', new_organization_path, class: "button" %>
<%= link_to 'Back', organizations_path, class: "button" %>

<p>
  <ul>
    <% @organizations.each do |organization| %>
      <li><%= link_to organization.name, organization %> | (<%= organization.donors.count%>)</li>
    <% end %>
  </ul>
</p>

<%= will_paginate %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form' %>

<%= link_to 'Back', donors_path %>

app/views/organizations/show.html.erb
<h2><%= @organization.name %></h2>
<%= link_to 'Edit Organization', edit_organization_path(@organization.id), class: "button tiny" %>
<%= link_to 'Destroy Organization', @organization, method: :delete, data: { confirm: 'Are you sure?' }, class: "button tiny" %>

<% if @organization.donations.count > 0 %>
  <% @organization.donations.each do |donation| %>
    <ul>
    <% unless donation.donor == nil %>
      <li>$<%= donation.amount %> on <%= donation.date.strftime("%m/%d/%Y") %> by <%= link_to donation.donor.name, donor_path(donation.donor.id) %> | <%= link_to 'Edit', edit_donation_path(donation.id) %> | <%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></li>
    <% end %>
    </ul>
  <% end %>
<% else %>
  <p>No donations to show.</p>
<% end %>

<%= link_to 'New Donation', new_donation_path(@donation), class: "button" %>

<%= link_to 'Back', organizations_path, class: "button" %>